### ISSUE TITLE
no FC connected when close

### ISSUE THREAD

**Issue by Jai-GAY** [ArduPilot/MethodicConfigurator#2]
just to highlight if users click close when no FC connected.

system
Edition	Windows 10 Pro
Version	22H2
OS build	19045.4291
Experience	Windows Feature Experience Pack 1000.19056.1000.0

![v0 2 0](https://github.com/ArduPilot/MethodicConfigurator/assets/12781023/b19e9ba5-9b8f-4190-89d5-786a3096205e)

**Comment by amilcarlucas** [comment]
Thanks for the report, I'll fix that.

**Comment by amilcarlucas** [comment]
It is fixed now. Thanks for the report
