### ISSUE TITLE
Version info

### ISSUE THREAD

**Issue by Jai-GAY** [ArduPilot/MethodicConfigurator#20]
Is there another easier way to determine the version of the app installed for Windows? Yes, the user can go a long way to Settings->Apps-> Search for the app.

Can the version info be in the GUI? 

![image](https://github.com/ArduPilot/MethodicConfigurator/assets/12781023/2dbff6bc-d569-4ecc-b196-7b190d6d0c4d)

**Comment by amilcarlucas** [comment]
In the command line:
```
ardupilot_methodic_configurator.exe --version
```

The version info is in the title of almost all *methodic configurator* windows
