### ISSUE TITLE
No vehicle_templates folder on linux (pip installation)

### ISSUE THREAD

**Issue by alexandru-g** [ArduPilot/MethodicConfigurator#47]
**Describe the bug**
Fresh install of MethodicConfigurator on Linux Mint using miniconda. There is no `miniconda3/lib/python3.10/site-packages/MethodicConfigurator/vehicle_templates` folder and I cannot start using the software (it needs to create a config for my copter and throws an error that there is no templates folder. I've searched for that folder in case it was a python issue but there wasn't one anywhere.

**To Reproduce**

1. Start MethodicConfigurator
2. Click on 'Create vehicle configuration directory from template'

**Expected behavior**
The `vehicle_templates` folder should be present.

**Screenshots**
![image](https://github.com/user-attachments/assets/86663937-1d30-4ce3-bb35-90cc29b4f6ab)
![image](https://github.com/user-attachments/assets/b835c79d-95d7-4d5c-aa88-3a95b32c82aa)

**Desktop (please complete the following information):**

- OS: Linux Mint
- Version: 22

**ArduPilot context**

- ArduPilot version: compiled from master
- Flight controller hardware: JHEMCU GHF745AIO (ported Ardupilot for it)

**Comment by alexandru-g** [comment]
For my use I just copied the folder from the repo to that location.

**Comment by amilcarlucas** [comment]
Yes, that is a known issue, the source pip package does contain the files but the binary pip package does not. PR's are welcome.
The solution you found is the same I use :-P

**Comment by amilcarlucas** [comment]
A workaround is:

```bash
git clone https://github.com/ArduPilot/MethodicConfigurator.git
cd MethodicConfigurator
./install_linux.sh
```
