### ISSUE TITLE
Clicking Links to the Forum Blog or Wiki Throws Error

### ISSUE THREAD

**Issue by timarcher** [ArduPilot/MethodicConfigurator#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

I am running the latest 0.9.16 tool.
When clicking on the link on any config page now, it throws an error.
Note, the web pages DO open up automatically when I navigate to any specific config step. Its just if I click the link to open the page as well it throws an error.
I am running Windows 11 and Chrome Browser.,

### Steps To Reproduce

Navigate to a step in the methodic configurator. For example 28_evaluate_the_aircraft_tune_ff_disable.param
Click on the links under Forum Blog or Wiki.
The page will not open, and an exception is shown in the dos window,

### Expected behavior

The selected link should open in my browser window.

### Screenshots / Logs

![image](https://github.com/user-attachments/assets/3fa15570-733d-4671-ad81-3a9a7b49e466)

![image](https://github.com/user-attachments/assets/0822d745-8327-4848-afb1-3a8eb546f357)

### Software information

- Operating system: Windows 11. Chrome Browser.
- arduPilot Methodic Configuration version: 0.9.16

**Comment by amilcarlucas** [comment]
Thanks for the report. I will look into it.
